### ISSUE TITLE
Tests fail using Node 17 and 18 and 19

### ISSUE THREAD

**Issue by dboreham** [cerc-io/laconic-sdk#6]
This repo's tests (`yarn test`) only work when run with Node 16. Run under Node 17 and 18 and 4 tests will fail that pass using Node 16.

**Comment by dboreham** [comment]
Now we're on to 19.

**Comment by zramsay** [comment]
just running `yarn` per the install instructions using version 17 didn't work. 16 worked

**Comment by dboreham** [comment]
This seems to be fixed now:

```
Test Suites: 7 passed, 7 total
Tests:       40 passed, 40 total
Snapshots:   0 total
Time:        222.173 s
Ran all test suites.
Done in 224.78s.
$ node --version
v18.15.0
$
```
