### ISSUE TITLE
Tests fail after recent changes in laconicd

### ISSUE THREAD

**Issue by nikugogoi** [cerc-io/laconic-sdk#8]
Test suite in `laconic-sdk` fails when running laconicd with changes in https://github.com/cerc-io/laconicd/pull/40

Error
```
errUnknownField "*types.Any": {TagNum: 12, WireType:"fixed32"}: tx parse error
```
[Full failing test-suite output](https://gist.github.com/nikugogoi/d974190a96fbf9376601da446f06ba0b#file-laconic-sdk-failing-test-log)

**Comment by dboreham** [comment]
Is this due to a bug in the new laconicd code, or were the tests not originally correct?

**Comment by ashwinphatak** [comment]
> Is this due to a bug in the new laconicd code, or were the tests not originally correct?

The tests all pass prior to PR 40 landing.

**Comment by dboreham** [comment]
> > Is this due to a bug in the new laconicd code, or were the tests not originally correct?
> 
> The tests all pass prior to PR 40 landing.

Should there be a bug filed in the laconicd project? (or should this bug have been filed there?)

**Comment by 0xmuralik** [comment]
> > Is this due to a bug in the new laconicd code, or were the tests not originally correct?
> 
> The tests all pass prior to PR 40 landing.

One of the tests on laconic-sdk which is failing now is sendning funds from one account to other ([get balance test](https://github.com/cerc-io/laconic-sdk/blob/3a890ab46cc6168cfc678121c9f0a41bfb304fa7/src/index.test.ts#L32)). I tried to do the same on laconicd directly which worked fine.
Also in the PR #40 we upgraded to cosmos-sdk v0.46.3 from v0.46.2. Could this be the reason why laconic-sdk is failing to complete transactions?

**Comment by 0xmuralik** [comment]
Just to be sure this is the error being returned for every failing test right?
`signature verification failed; please verify account number (0) and chain-id (ethermint_9000-1): feePayer pubkey EthPubKeySecp256k1{0233C41D160405A0E97DB0D18B9B26F7DBD21014300CC3B92357FF663F6880ADCF} is different from transaction pubkey EthPubKeySecp256k1{021DE395EE8B253EE9921F44F3638E3D19143ED9E7CEFBCC5293384425F1B1C34E}: invalid pubkey [cerc-io/laconicd/app/ante/eip712.go:251]: unauthorized`

**Comment by i-norden** [comment]
I don't see that error in the linked test output, just seeing a bunch of 

```
errUnknownField "*types.Any": {TagNum: 12, WireType:"fixed32"}: tx parse error

      114 |
      115 |     if (!errorMessage) {
    > 116 |       console.error(error)
          |               ^
      117 |     }
      118 |
      119 |     return errorMessage || DEFAULT_WRITE_ERROR;

      at Function.processWriteError (src/index.ts:116:15)
      at Registry.<anonymous> (src/index.ts:539:32)
      at fulfilled (src/index.ts:5:58)
```

**Comment by i-norden** [comment]
The error trace doesn't seem to suggest an issue with the code implemented in laconicd, but rather some incompatability between laconic-sdk and the new v0.46.3 version of the cosmos-sdk being used as a dependency in laconicd. But, as Murali pointed out elsewhere, the upgrade was only from v0.46.2 => v0.46.3 and really shouldn't include breaking changes.

**Comment by 0xmuralik** [comment]
@nikugogoi I am not able to recreate the error log mentioned in the issue. Im gettting a bunch of `signature verification failed` errors. Could you help me recreate this?

**Comment by nikugogoi** [comment]
> I am gettting a bunch of `signature verification failed` errors. Could you help me recreate this?

The `signature verification failed` errors must be because of the mismatch in chain ID. The [chain ID in `laconicd`](https://github.com/cerc-io/laconicd/blob/main/init.sh#L4) and the [chain ID in `laconic-sdk`](https://github.com/cerc-io/laconic-sdk/blob/main/src/index.ts#L56) (which can be set as `COSMOS_CHAIN_ID` in `.env` file) must be same.

Previously, the chain ID in laconicd was `laconic_9000-1`.

On running the test now against latest laconicd I am getting a different error
`unable to resolve type URL /vulcanize.nameservice.v1beta1.MsgSetRecord: tx parse error`
[Full failing test-suite output](https://gist.github.com/nikugogoi/25b945c1c6655e91d791ad334a4a6ccb)
